### ISSUE TITLE
Finish group contract

### ISSUE THREAD

**Issue by Didgy74** [cecilianor/Qt-thesis#2]
Estimate: 4 hours

Once completed, this updates #3 and is a part of both the project plan delivery and the **final report**. Remember that Cecilia moved it to a new Overleaf document

# Sections in the group contract
- [x] Role and Responsibilities
- [x] Expectations of the Workflow
- [x] Distribution of the Workload
- [x] Contact Information

**Comment by cecilianor** [comment]
I don't think I have anything else to add to the group contract. I cleaned up minor errors, added some details, and have also put a signature section on the bottom. Could you guys take a look at it and approve it tomorrow? @Didgy74 @EimenOueslati

**Comment by cecilianor** [comment]
This has been completed, but feel free to make minor edits if something is missing.
