### ISSUE TITLE
Report: Design Overall System Architecture

### ISSUE THREAD

**Issue by cecilianor** [cecilianor/Qt-thesis#22]
The overall architecture of the system must be designed.

Qt has offered to create the entire architecture for us, but we should consult with Xiang if that's a good idea before we offload this work to them. 

It may be recommended or required that we - the student team - design the architecture ourselves since it may be a crucial part of the final report. If we ask Qt to do it for us, we should bring up in the report why it was done this way. If we end up making the architecture ourselves, Qt would like to supervise it so that the system gets designed the best way possible. This would be done to avoid having to make major revisions later that would force the project to start over again.

This issue updates #20 once completed.

**Comment by Didgy74** [comment]
Nils will be taking charge of this for beginning of sprint 3
