### ISSUE TITLE
Loading tiles: Download from MapTiler

### ISSUE THREAD

**Issue by Didgy74** [cecilianor/Qt-thesis#26]
To complete this task, the following must be completed:
- [ ] Set up HTTP handling functionality in the HTTPHandler class.
  - [x] Get style.json files
  - [x] Implement basic HTTP error handling functionality that returns appropriate errors upon failure to grab style.json content.
  - [x] Get protobuf files
  - [x] Implement basic HTTP error handling functionality that returns appropriate errors upon failure to grab pbf content.
- [x] Instantiate the HTTP handler in main and call the HTTP handling functionality:
  - [x] Get stylesheets (style.json)
  - [x] Get sources from stylesheet (tiles.json)
  - [x] Make a get request to the tiles.json file. The response will have a `"tiles" : ["link"]` section at the end/bottom. Save this link.
  - [x] Make a get request to the link that was located in `"tiles": ["link"]` to get the XYZ `.pbf` files.
- [x] Implement functionality that can grab any XYZ indices

**Comment by cecilianor** [comment]
This is complete. I'm closing the issue now.
