### ISSUE TITLE
getTile unit tests

### ISSUE THREAD

**Issue by Didgy74** [cecilianor/Qt-thesis#37]
## Critical information about this issue
This issue should not cover testing of making HTTP request, that kind of test will be made later if viable. 

This issue is dedicated to writing unit tests for the getTile functionality. In the future, we will also set up HTTP error testing if we can figure that out, but this will happen a bit further down the line. Cecilia will research if/how it's feasible to make HTTP request tests before we add it as an actual issue and start implementing this.

Parent issue: #43

**Comment by cecilianor** [comment]
The getTile functionality has been refactored, and a lot of the functionality has been moved or doesn't exist anymore. I'm closing this issue based on that.
