### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by cecilianor** [cecilianor/Qt-thesis#43]
Everyone should start implementing unit tests on the software they have developed. We should also agree on what code coverage we want. 

Siamak Khatami said that there is norm in the software industry to aim for 80 % code coverage, but that it's ultimately up to the development team to decide. Cecilia votes for 80 % just to follow that but doesn't feel strongly about this.

Sections that can have unit tests:
- [x] GetTile class
- [x] Others?

Child issue:(s) #37

**Comment by Didgy74** [comment]
Nils will help write unit tests.

**Comment by cecilianor** [comment]
We have made the initial unit tests. Note that code coverage won't apply to our case anymore since we never got the Coco code coverage tool to work. Supervisor Rafael Palomar has advised that a code coverage report doesn't really matter that much. Our goal going forward should be to make as many unit tests as possible, so that's our goal going forward.
