### ISSUE TITLE
Interactivity: Cursor drag panning

### ISSUE THREAD

**Issue by Didgy74** [cecilianor/Qt-thesis#57]
This issue might not end up being implemented.

Make it so the cursor can be held and dragged to pan the map viewport.

**Comment by Didgy74** [comment]
If we finish, make another Git issue for scrollwheel zooming.

**Comment by cecilianor** [comment]
This is actually mostly completed, both for the map dragging and the mousewheel zooming. The only thing that still needs some work is to zoom on the cursor itself, and there is a viewport bug when the screen isn't perfectly square. When these issues are addressed, the issue is complete.
