### ISSUE TITLE
Tasks before the next merge from dev  to main

### ISSUE THREAD

**Issue by cecilianor** [cecilianor/Qt-thesis#89]
# General Tasks
Tasks we need to do to merge the dev branch into main:

- [ ] Nils: Fix incorrect placement or size of tiles that's causing lines to appear between tiles on the map (already done by Matthias)
  - Do not merge mouse interactions made by Matthias into main, they can stay on a separate branch until after delivery
- [x] Cecilia: Separate rendering code that's currently on `Rendering.cpp` onto multiple files: `Rendering.cpp`,  `Rendering_Math.cpp`, `Rendering_Text.cpp`
- [x] All: All rendering code needs to be doc commented and internally commented, see issue #83 as well, and update that one when this is completed
- [x] Nils and Eimen: Memory leak in stylesheet
- [x] Cecilia: Merge Rafael's work into unit test branch, then merge the unit test branch into `dev`, check that all tests still work, and finally pull into main

# Individual Commenting
Commenting of files. Update doc comments to QDoc:
- [x] Nils: `Utilities.cpp` and `Utilities.h`
- [x] Cecilia: `Layerstyle.cpp` and `TileCoord.h`
- [x] Eimen: Update `Evaluator.cpp` and `VectorTiles.cpp`

**Comment by cecilianor** [comment]
I am about to merge a large set of changes in to `dev`. These changes are just sorting out the project header include sections, so all of the functionality should remain the same. Let me know if something got lost on the way here.

**Comment by Didgy74** [comment]
- [ ] Fix memory leaks
- [ ] Fix top level world map not being rendered #94
